config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  resources :posts do
    resources :comments

    collection do
      get :latest

      post :bulk_update
    end

    member do
      get :dashboard
    end
  end

  namespace :admin do
    resources :posts
  end

  root :to => 'posts#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates_presence_of :content

  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates_presence_of :title, :content

  belongs_to :user
  belongs_to :category

  has_many :comments
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments

  def short_name
    self.email.split('@').first
  end

  def admin?
    self.role == "admin"
  end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController

  before_action :authenticate_user!

  before_action :check_admin

  layout "admin"

  def index
    @posts = Post.all
  end

    protected

    # def authenticate
    #   authenticate_or_request_with_http_basic do |user_name, password|
    #     user_name == 'username' && password == 'password'
    #   end
    # end


    def check_admin
      unless current_user.admin?
        raise ActiveRecord::RecordNotFound
      end
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  before_action :configure_permitted_parameters, if: :devise_controller?

  protect_from_forgery with: :exception

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :last_name])
    # devise_parameter_sanitizer.permit(:sign_up) << :last_name

    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :last_name])
    # devise_parameter_sanitizer.permit(:account_update) << :last_name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user! # check if the user has logged in
  before_action :set_post

  def create
    @comment = @post.comments.new(comment_params) # @comment.post_id == @post.id

    @comment.user = current_user
    # @comment belongs to current_user
    # @comment.user_id == current_user.id
    if @comment.save
      # @post.number_of_comments += 1
      # @post.save
    end

    redirect_to post_path(@post)
  end

  def edit
    @comment = @post.comments.find_by_id(params[:id])
    if @comment.user != current_user
      flash[:alert] = 'yo bro you don\'t have the authority to edit this comment'
    end
  end

  def update
    @comment = @post.comments.find_by_id(params[:id])
    if @comment.user == current_user
      @comment.update(comment_params)
      flash[:notice] = 'Your comment update has been saved:)'
    end
    redirect_to post_path(@post)
  end


  def destroy
    @comment = @post.comments.find_by_id(params[:id])
    if @comment.user == current_user # user can only destroy his/her own comments
      # check if the author of the comment is equal to current_user
      if @comment.destroy
        # number of comments -= 1
      end

      flash[:notice] = 'You\'ve deleted the comment.'
    else
      flash[:alert] = 'You don\'t have the authority to delete any comment...'
    end

    redirect_to :back
  end

  protected

  def set_post
    @post = Post.find(params[:post_id])
  end


  def comment_params
    params.require(:comment).permit(:content, :post_id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, :only => [:show, :edit, :update, :destroy, :dashboard]
  before_action :authenticate_user!, :except => [:index, :show]

  def index
    prepare_variable_for_index_template
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      redirect_to posts_path
      flash[:notice] = 'The post has been saved:)'
    end
  end

  def show
    @comment = Comment.new
  end

  def edit
  end

  def update
    if @post.update(post_params)
      redirect_to post_path(@post)
    else
      render :edit
    end
  end

  def destroy
    if @post.user == current_user
      @post.destroy

      flash[:notice] = 'Congrats, your post has been removed!'
    else
      flash[:alert] = 'Nothing has been destroyed:('
    end

    redirect_to posts_path
  end

  # get /events/latest
  def latest
    @posts = Post.order('id DESC').limit(3)
  end

  def bulk_update
    ids = Array( params[:ids] )
    posts = ids.map{ |i| Post.find_by_id(i) }.compact

    if params[:commit] == 'Delete'
      posts.each { |p| p.destroy }
    elsif params[:commit] == 'Publish'
      posts.each { |p| p.update( :status => 'published') }
    end

    redirect_to :back
  end

  def dashboard

  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :category_id, :status)
  end

  def prepare_variable_for_index_template
    if params[:keyword]
      @posts = Post.where( [ "title like ?", "%#{params[:keyword]}%" ] )
    else
      @posts = Post.all
    end

    if params[:order]
      sort_by = (params[:order] == 'title') ? 'title' : 'id'
      @posts = @posts.order(sort_by)
    end

    @posts = @posts.page(params[:page]).per(5)
    #.order('created_at DESC')

  end
end

app/helpers/admin/posts_helper.rb
module Admin::PostsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admin/posts/index.html.erb
Posts admin page!

app/views/comments/edit.html.erb
<div class='form-group'>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content, 'Comment' %>
  <%= f.text_area :content %>

  <%= f.submit 'Save Update' %>
<% end %>
</div>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HsMidtermBackend9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>
<h1>Admin Interface</h1>
<h1 class='title' style='color: #410c7a'>災情速速報</h1>

<%= link_to '張貼新災情資訊', new_post_path %>

<p style='color:green'><%= notice %></p>
<p style='color:red'><%= alert %></p>


<%= yield %>


<%= link_to 'admin', admin_posts_path %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HsMidtermBackend9</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if current_user %>
  <p>Hi, <%= current_user.name %>!</p>
  <%= link_to('登出', destroy_user_session_path, :method => :delete) %> |
  <%= link_to('修改密碼', edit_registration_path(:user)) %>
<% else %>
  <%= link_to('註冊', new_registration_path(:user)) %> |
  <%= link_to('登入', new_session_path(:user)) %>
<% end %>

<h1 class='title' style='color: #410c7a'>災情速速報</h1>

<%= link_to '張貼新災情資訊', new_post_path %>

<p style='color:green'><%= notice %></p>
<p style='color:red'><%= alert %></p>

<% if current_user && current_user.admin? %>
  <%= link_to 'admin', admin_posts_path, :class => 'btn btn-info'%>
<% end %>

<%= yield %>


</body>
</html>

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
  <ul>
    <% @post.erros.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/posts/dashboard.html.erb
<h3>The Dashboard of <b><i><%= @post.title %></i></b></h3>

app/views/posts/edit.html.erb
<%= form_for @post, :url => post_path(@post), :method => :patch do |f| %>

<div class='form-group'>
  <%= f.label :title, 'Title' %>
  <%= f.text_field :title, :required => true, :class => 'form-control' %>
</div>

<div class='form-group'>
  <%= f.label :status, 'Status' %>
  <%= f.select :status, [ ["Published", "PUBLISHED"], ["Draft", "DRAFT"] ] %>
</div>
<div class='form-group'>
  <%= f.label 'Category' %>
  <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  <%= f.select :category_id, Category.all.map{ |x| [x.name, x.id] }, :class => 'form-control' %>
  <% Category.all.each do |c| %>
    <%= f.radio_button :category_id, c.id %> <%= c.name %>
  <% end %>
</div>
<div class='form-group'>
  <%= f.label :content, 'Content' %>
  <%= f.text_area :content %>
</div>

  <%= f.submit 'Finishing Editing' %>

<% end %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p>
  <%= link_to 'Latest events', latest_posts_path %>
</p>

<%= form_tag posts_path, :method => :get do %>
  <%= text_field_tag 'keyword' %>
  <%= submit_tag 'Search' %>
<% end %>

<br>

<%= form_tag bulk_update_posts_path do %>
  <%= link_to 'Sort by name', posts_path( :order => 'title' ) %>
  <%= link_to 'Sort by Default', posts_path %>

  <br>

  <table class='table col-md-12'>
    <tr>
      <th colspan='3'>Title</th>
      <th colspan='3'>User</th>
      <th colspan='3'>Category</th>
      <th colspan='3'>Submit Time</th>
    </tr>
    <% @posts.each do |p| %>
      <tr>

          <td colspan='3'>
            <%= check_box_tag "ids[]", p.id, false %>
            <%= link_to p.title, post_path(p)  %>
          </td>
          <td colspan='3'>
            <%= p.user.try(:short_name) %>
          </td>
          <td colspan='3'><%= p.category.try(:name) %></td>
          <td colspan='3'><%= p.created_at %></td>
          <td colspan='3'>
            <%= link_to 'Edit', edit_post_path(p), :class => 'btn btn-default' %>
            <%= link_to 'Delete', post_path(p), :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'btn btn-danger' %>
            <%= link_to 'Comments', post_comments_path(p), :class => 'btn btn-primary' %>
            <%= link_to 'Dashboard', dashboard_post_path(p), :class => 'btn btn-link' %>
          </td>
      </tr>
    <% end %>
  </table>

  <%= submit_tag 'Delete' %>
  <%= submit_tag 'Publish' %>

<% end %>

<br>
<ul style='list-style: none'>
  <li>Total number of posts: <%= Post.all.size %></li>
  <li>Total number of comments: <%= Comment.all.size %></li>
</ul>

<%= paginate @posts %>

app/views/posts/latest.html.erb
<% @posts.each do |post| %>
  <ul>
    <li><%= post.title %></li>
  </ul>

<% end %>

app/views/posts/new.html.erb
<%= form_for @post do |f| %>

  <p>
    <%= f.label 'Title' %>
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label 'Category' %>
    <%= f.collection_select(:category_id, Category.all, :id, :name) %>
  </p>

  <div class='form-group'>
    <%= f.label :status, 'Status' %>
    <%= f.select :status, [ ["Published", "PUBLISHED"], ["Draft", "DRAFT"]] %>
  </div>
  <p>
    <%= f.label 'Content' %>
    <%= f.text_area :content %>
  </p>

  <%= f.submit 'Creadte New Post' %>
<% end %>

app/views/posts/show.html.erb
<h1 class='title'><%= @post.title %></h1>

<!-- <p><%= @post.content %></p> -->
<div class='form-group'>
<h3><%= @post.category.try(:name) %></h3>

<p><%= @post.status %></p>

<%= simple_format(@post.content) %>

<%= link_to 'Back', posts_path, :method => :get, :class => 'btn btn-primary' %>
<%= link_to 'Edit Post', edit_post_path(@post), :class => 'btn btn-default' %>
<%= link_to 'Delete Post', post_path(@post), :method => :delete, :data => { :confirm => 'You sure you wanna delete this post, bro?' }, :class => 'btn btn-danger' %>
</div>

<div class='form-group'>
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content, 'Comment' %>
  <%= f.text_area :content %>

  <%= f.submit 'Post New Comment' %>
<% end %>
</div>

<h3>Past Comments</h3>
<p>There are <%= @post.comments.size %> comments in this post.</p>

<table class='table-bordered table-striped col-md-12 table-hover'>
  <tr>
    <th class='text-center'>Comment</th>
  </tr>
  <% @post.comments.each do |c| %>
    <tr>
      <td class='col-md-10'><%= c.content %></td>
      <td class='col-md-1 text-center'>
        <% if c.user == current_user %>
          <%= link_to 'Edit', edit_post_comment_path(@post, c) %>
        <% end %>
      </td>
      <td class='col-md-1 text-center'>
        <% if c.user == current_user %>
          <%= link_to 'Delete', post_comment_path(@post, c), :method => :delete, :data => { :confirm => 'Are you sure????' } %>
        <% end %>
      </td>

    </tr>
  <% end %>

</table>